env:
  global:
    - CC_TEST_REPORTER_ID=<45db4b0cb11303088f5b5f8348f5b6fd320181233778fe51211529b7e0c224ff>
language: ruby
rvm:
  - 2.6.0
  - jruby
before_install: 
  - gem update --system
  - gem install bundler
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  — bundle install
  - bundle exec rspec spec
  # - bundle exec rake spec

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

  # adding comment for commit
