env:
  global:
    - CC_TEST_REPORTER_ID=<9763919d7119e0e727f8cf7f54965b3db2290237c7c58f1a659960456421fc74>
language: ruby
rvm:
  - 2.6.0
before_install:
  - gem install bundler
  - gem update --system

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - export CC_TEST_REPORTER_ID=<9763919d7119e0e727f8cf7f54965b3db2290237c7c58f1a659960456421fc74> cc-test-reporter after-build --exit-code $?
  # - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT